name: fellas
version: '1.0-SNAPSHOT'
main: miao.fellas.Fellas
api-version: '26.1.2'
softdepend:
  - Vault
commands:
  send:
    description: Sends a message to the sender
    usage: /send [player] [message]

  kit:
    description: Gives the selected kit
    usage: /kit <kit>

  kitreload:
    description: reloads kits from the config.yml
    usage: /kitreload
    permission: fellas.kit.reload

  kits:
    description: Shows the list of the available kits
    usage: /kits






permissions:
  fellas.send:
    description: Grants the use of /message
    default: op

  fellas.kit:
    description: Grants the use of /kit
    default: true

  fellas.kit.reload:
    description: Grants the use of /kitreload
    default: op

  fellas.kit.bypasscooldown:
    description: Allows bypassing kit cooldown
    default: op

  fellas.kit.allkits:
    description: Grants the access to all kits
    default: op

  fellas.kit.admin:
    description: Grants all the admin commands for kits
    default: op
    children:
      fellas.kit.bypasscooldown: true
      fellas.kit.reload: true
      fellas.kit.allkits: true

  fellas.kits:
    description: grants the use of /kits
    default: true