kits:
  starter:
    price: 100
    permission: fellas.kit.starter
    cooldown: 60
    items:
      - IRON_SWORD:1
      - COOKED_BEEF:8
  pvp:
    price: 250
    permission: fellas.kit.pvp
    cooldown: 600
    items:
      - DIAMOND_SWORD:1
      - GOLDEN_APPLE:4
      - IRON_CHESTPLATE:1
  archer:
    price: 200
    permission: fellas.kit.archer
    cooldown: 600
    items:
      - BOW:1
      - LEATHER_LEGGINGS:1
      - LEATHER_CHESTPLATE:1
      - GOLDEN_APPLE:8
      - ARROW:64
messages:
  noPermission: "<red>Insufficient permissions.</red> <dark_purple>({permission})</dark_purple>"
  onlyPlayer: "Only players may use this command"
  kitNotFound: "<red>This kit does not exist.</red>"
  kitUsage: "<red>Usage: /kit [kit]</red>"
  economyDisabled: "<red>Economy is temporarily disabled. This kit cannot be claimed.</red>"
  kitCooldown: "<red>Kit still in cooldown, remaining time: </red><dark_purple>{remainingCooldown}s</dark_purple><red>.</red>"
  kitClaimed: "<dark_purple>Kit {kitName} has been claimed!</dark_purple>"
  kitPurchase: "<dark_purple>Kit {kitName} has been purchased!</dark_purple> <yellow>New balance:</yellow> <green>€{balance}</green>"
  transactionFailed: "<red>Transaction failed.</red>"
  notEnoughMoney: "<red>You don't have enough money to claim this kit</red>"
  kitReload: "<green>Kits reloaded.</green>"
  kitsWithCooldown: "<blue>{kitName}</blue> <dark_purple>-</dark_purple> <yellow>price:</yellow> <green>€{price}</green> <dark_purple>-</dark_purple> <yellow>cooldown: {remainingCooldown}</yellow><dark_purple>/</dark_purple><yellow>{cooldown}s.</yellow>"
  kitsWoutCooldown: "<blue>{kitName}</blue> <dark_purple>-</dark_purple> <yellow>price:</yellow> <green>€{price}</green> <dark_purple>-</dark_purple> <yellow>cooldown: </yellow><green>ready.</green>"
  kitsNotOne: "<red>No kits available.</red>"
  kitsHeader: "<dark_purple>Available kits:</dark_purple>"
  sendTargetMissing: "<red>Target player missing.</red>"
  sendTargetNotOnline: "<red>{player} is not online.</red>"
  sendMessageMissing: "<red>Message missing.</red>"
  sendMessageSent: "<blue>{sender}</blue> <dark_purple>sent you a message: </dark_purple>{message}"

