name: fellas
version: '1.0-SNAPSHOT'
main: miao.fellas.Fellas
api-version: '26.1.2'
commands:
  messaggio:
    description: Invia un messaggio al giocatore
    usage: /messaggio [messaggio]
    permission: fellas.message

  kit:
    description: Da al player un kit
    usage: /kit <starter/pvp/archer>
    permission: fellas.kit

  kitreload:
    description: Ricarica i kit
    usage: /kitreload
    permission: fellas.kit.reload






permissions:
  fellas.message:
    description: Permette l'utilizzo del comando /messaggio
    default: op
  fellas.kit:
    description: Permette l'utilizzo del comando /kit
    default: true
  fellas.kit.reload:
    description: Permette di ricaricare i kit
    default: op
