name: fellas
version: '1.0-SNAPSHOT'
main: miao.fellas.Fellas
api-version: '26.1.2'
commands:
  messaggio:
    description: Sends a message to the sender
    usage: /message [message]
    permission: fellas.message

  kit:
    description: Gives the selected kit
    usage: /kit <starter/pvp/archer>
    permission: fellas.kit

  kitreload:
    description: reloads the kit detection
    usage: /kitreload
    permission: fellas.kit.reload






permissions:
  fellas.message:
    description: Grants the use of /message
    default: op
  fellas.kit:
    description: Grants the use of /kit
    default: true
  fellas.kit.reload:
    description: Grants the use of /kitreload
    default: op
